name: discord-watchdog-haskell
version: 0.0.0.0
github: "approvers/discord-watchdog-haskell"
license: MIT
author: "SHUN/しゅん"
maintainer: "shun.shobon@gmail.com"
copyright: "2020 SHUN/しゅん"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis: Short description of your package
# category: App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Discordのサーバーを監視し、必要な場合は警告します。

dependencies:
  - base >= 4.7 && < 5
  - text
  - emoji
  - discord-haskell
  - dotenv

library:
  source-dirs: src

executables:
  discord-watchdog-haskell-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - discord-watchdog-haskell

tests:
  discord-watchdog-haskell-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - discord-watchdog-haskell
